# database properties (configure to run on local)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_natura?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&max_allowed_packet=32M
    username: naturauser
    password: natura
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect